const nameOnPass = "Oscar";
console.log(nameOnPass)
const nameOnId = "Oscar";
const nameMatch = nameOnId === nameOnPass;
console.log("ID confirmed? " + nameMatch);
const length = 25;
const isLengthExcess = length <= 30;
const height = 30;
const isHeightExcess = height <= 55;
const isHandBaggageEligible = isLengthExcess && isHeightExcess;
console.log("Is Hand Baggage Eligible? " + isHandBaggageEligible);
const flightDes = "AMS";
const returnFrom = "LGW";
const isRoundTrip = flightDes === returnFrom;
console.log("Round Trip Check? " + isRoundTrip);
const bookings = 80;
const totalCapacity = 120;
const isFlightAvailable = bookings <= totalCapacity;
console.log("Are Seats Available? " + isFlightAvailable);
document.querySelector("#name").innerHTML = nameOnPass;
document.querySelector("#id").innerHTML = nameMatch;
document.querySelector("#bag").innerHTML = isHandBaggageEligible;
document.querySelector("#des").innerHTML = isRoundTrip;
document.querySelector("#seat").innerHTML = isFlightAvailable;